filename : '/home/itumusiime/Documents/Applications/Assessment/loans.csv'
loan_profile : '/home/itumusiime/Documents/ML/projects/loan_report.html'
port: 2525
smtp_server : "smtp.mailtrap.io"
login : "562cd2cbe37a29"
password : "2f1234e7332629"
subject : "ETL Pipeline Results"
sender_email : "sender@mailtrap.io"
receiver_email : "receiver@mailtrap.io"
dw_string : "host='localhost' dbname='dw1' user='dw' password='dwhouse'"
preserved_file : fr'/home/itumusiime/Documents/ML/projects/data{timestr}.csv'